### ISSUE TITLE
Looking for someone to take over active maintenance of Apaxy

### ISSUE THREAD

**Issue by AdamWhitcroft** [oupala/apaxy#101]
Hey there,

I'm looking for someone who'd be interested in taking over the active maintenance of Apaxy moving forward. I don't have the time available right now to give it the attention it deserves, and I don't want to let people down by letting the repo go stale.

If you're interested, let me know below and we'll figure out the best way to move it forward.

cc @oupala

**Comment by rivermont** [comment]
I'm interested. Not sure how full-time I would be able to be but I could handle PRs and Issues. I haven't used Apache for long so active development might not be a thing for me.

**Comment by oupala** [comment]
I'm also ok to maintain apaxy as I'm using it. I don't want to be the only maintainer so sharing this role with someone else is ok for me (maybe @rivermont ?).

**Comment by jordanbancino** [comment]
I have used Apaxy for a little while, and customized it quite a bit on my system. I think I could maintain it. I definitely have the time

**Comment by oupala** [comment]
As far as I understand, @jordanbancino could be the official maintainer of apaxy, helped by @rivermont and myself. Could you please @AdamWhitcroft tell us what you think of this threesome proposal?

If you need more information, each of us can tell you in a few lines what we think about the futur of apaxy. That could be a good way to check that we all share the same thoughts about it.

**Comment by oupala** [comment]
I see that @chrisssycollins has also proposed in #103 to share the governance of apaxy, and has already share his toughts about apaxy.

**Comment by oupala** [comment]
So let's start and share my thoughts: I don't have a particular opinion about what should the futur of apaxy. I just like to keep it (simple) stupid, easy to install anywhere, without much requirements (an httpd server), easy to install in a root directory or in a subdirectory.

For the rest, I'd like the futur to be community driven, paying attention to all good wills, even small ones, to merge or close pending pull requests, to have a code of conduct.

**Comment by AdamWhitcroft** [comment]
Thanks for the replies everyone! @oupala you’ve been a consistent contributor to Apaxy so I’m happy to let you take it over (as part of the quartet!).

What do I need to do for that to happen?

**Comment by oupala** [comment]
Great news @AdamWhitcroft.

You can transfer your repo to me following instructions from [GitHub help](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization).

**Comment by oupala** [comment]
Thank you @AdamWhitcroft . The repo has been transferred. Let's start to work!

To @rivermont, @jordanbancino and @chrissycollins, here are what I'd like us to do for now:

- [ ] respond to issues and close them if possible
- [ ] respond to pull requests and merge them if possible
- [ ] start to version Apaxy (what should be the first release? v1.0.0 ?)

Tell me what you think of these first steps.

**Comment by jordanbancino** [comment]
Ok. Sounds good!

On Feb 16, 2018 6:18 PM, "oupala" <notifications@github.com> wrote:

Thank you @AdamWhitcroft <https://github.com/adamwhitcroft> . The repo has
been transferred. Let's start to work!

To @rivermont <https://github.com/rivermont>, @jordanbancino
<https://github.com/jordanbancino> and @chrissycollins, here are what I'd
like us to do for now:

   - respond to issues and close them if possible
   - respond to pull requests and merge them if possible
   - start to version Apaxy (what should be the first release? v1.0.0 ?)

Tell me what you think of these first steps.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/oupala/apaxy/issues/101#issuecomment-366386532>, or mute
the thread

**Comment by rivermont** [comment]
Sounds like a plan!
I may only be a very partial maintainer (?) as school is taking over, but I'll do what I can.

I think it would be good to figure out what to do with icons, as there have been multiple pulls regarding compressing or changing them. I think one option might be to have large icons for those seeking quality and smaller icons for those looking to save space.

#63 and #99 reduce the size of icons without reducing quality much.
#45 and #86 add new icons for more file extensions
#103 Nicely redesigned all the things

@chrisssycollins Interested in the idea of the organization.
Just some thoughts!

**Comment by oupala** [comment]
Ok, regarding what you say, we won't merge all the pull request, it would be meaningless.

What should we prioritize? Icons size, new icons, new design?

What about merging #103? The last one and the one that reworked all icons (which makes previous PR irrelevant)?

It's always hard to manage old pull request. Some of them may not be inaccurate, the PR's author might have gone away, or can be demotivated... :sigh:

**Comment by chrisssycollins** [comment]
@rivermont @oupala Regarding quality and sizes of the icons. I created the icons in #103  from scratch, they are all vectors and can exported to any size and type we need. 

On the subject of PRs: 

I'd close the following due to either being fixed by another, really old or not bringing enough: 
#15 
#30 
#49 
#63 
#85
#88
#90 
#99

I'd keep open and either recreate (bring up to date) the changes or merge them directly: 
#45 (I'll handle this)
#64 
#82 
#86 (I'll handle updating this to new icons)
#102
#103

**Comment by oupala** [comment]
Thank you @chrisssycollins for your helpful answer. I followed most of your advices.

I also rebased develop onto master (sorry for rebasing a public branch) et release a v1.0.0 of apaxy. I think we needed a clear versionning and a clear base for managing changes.

v1.0.0 is more or less what we knew about apaxy for months. Let's start to work on feature branches and on develop branch to bring best changes to apaxy.

**Comment by PeterDaveHello** [comment]
I'd like to help.

**Comment by oupala** [comment]
@PeterDaveHello Please do. Do you know how you want to help or do you want us to tell you what to do?

**Comment by PeterDaveHello** [comment]
I maintain few projects including some famous(feel free to take a look at [my GitHub page](https://github.com/PeterDaveHello)), know about sysadmin, web dev,etc, so I'm fine to do what can I do, PR reviewing, issue management, discussion, etc.

**Comment by oupala** [comment]
Ok, the main task now is to review all issues and check if they are still valid with version 1.0.0 that I published yesterday.

**Comment by PeterDaveHello** [comment]
So I think I should be added as a collaborator so that I can do that?

**Comment by oupala** [comment]
@PeterDaveHello You can comment any issue without being a collaborator.

**Comment by PeterDaveHello** [comment]
Yes, but can't label, assign, or close any issues including pull requests, also can't merge pull request or review pull request with the review functions on GitHub, they are all very important part of maintenance, right?

**Comment by AdamWhitcroft** [comment]
Hey everyone, just wanted to thank you for your passion for taking over this project. I made it as a side thing over a weekend a while ago and it got a little bigger than I had anticipated, and I wasn't really in a position to give it the attention it needed. Really stoked that it's going to be looked after by such awesome people. 

Thanks for all of your support, and for taking the reins from here.

**Comment by PeterDaveHello** [comment]
Hey @AdamWhitcroft thanks for the project anyway, would you ever consider to move this project to an organization (Maybe just call it **Apaxy**!) so that you can still be an owner, one of the owners, and there can be few or more members to help maintain this project? As I think the permission and team management feature is lack in personal project, though I'm even not a collaborator yet, just my opinion.

**Comment by nodiscc** [comment]
Thanks @AdamWhitcroft for writing Apaxy and supporting it for so long! And everyone for keeping this running.

I use it daily for years as a static home server homepage. What I like about Apaxy: it's static, it works without JS, it's fast, it leverages basic apache functionality to do it's job, it rarely changes. My only "problem" so far is the external font (#59), I wish this could be made optional (maybe as part of https://github.com/oupala/apaxy/issues/107 config file + install script?). But keep it (simple) stupid :+1:

I won't have much time to help, but feel free to grab from here [[1]](https://github.com/nodiscc/srv01/blob/master/roles/apache2/tasks/apaxy.yml) [[2]](https://github.com/nodiscc/srv01/blob/master/roles/apache2/files/var_www_Apaxy_apaxy_.htaccess) (ansible tasks for apaxy installation/config, can easily be ported to bash I guess). We have also listed Apaxy in https://github.com/Kickball/awesome-selfhosted/#web-based-file-managers < -- hope this helps.

Cheers!

**Comment by PeterDaveHello** [comment]
@oupala can you please take a look at my previous comment? Thanks.

**Comment by oupala** [comment]
This is obviously something that we should do one day. However, we just took the task of maintaining apaxy from the original author @AdamWhitcroft. It is a bit too early to switch now to an organization.

But that's definitely something that we should do at some point. I don't see the point of keeping the ownership of this project for a long time. I only see it as a transitional phase.
