### ISSUE TITLE
.conf Icon

### ISSUE THREAD

**Issue by jordanbancino** [oupala/apaxy#111]
The icon for `.conf` files does not match the theme of apaxy. I'm guessing that `Apache` defaults `.conf` files to this, because apaxy does not even have a `.conf` icon.

![capture](https://user-images.githubusercontent.com/27834353/36603244-2ecd7716-1888-11e8-8530-4e9082cbf0c2.PNG)

**Comment by jordanbancino** [comment]
I drew up a quick icon: 
![conf](https://user-images.githubusercontent.com/27834353/36604188-fc6a1a60-188a-11e8-8872-c702372a3cd2.png)

Here's how it looks:
![capture](https://user-images.githubusercontent.com/27834353/36604198-060dd2dc-188b-11e8-8b5c-846ce6d2c09f.PNG)

**Comment by oupala** [comment]
Please make sure that @chrissycollins (wo works on pull request #103) that your icon is compatible with the ones from the pull request.

**Comment by jordanbancino** [comment]
I can do that, but that was more of a mock-up. I’m not a graphic designer, so I didn’t know if you guys would actually want it. The issue was more just to state the fact that we don’t have an icon for `.conf` file. I thought maybe someone else might want to make an icon for it or something.

**Comment by oupala** [comment]
@chrisssycollins can tell you if he has a conf icon in his new set.
