### ISSUE TITLE
Parametrize {FOLDERNAME}

### ISSUE THREAD

**Issue by pcav** [oupala/apaxy#113]
If put in a variable, user can change it only once for the whole htaccess

**Comment by jordanbancino** [comment]
I agree, this is desirable. But does anyone know if this is even possible? A quick google search brings up nothing on placing variables in `.htaccess`. But if we could somehow accomplish this, then I could probably close #107

**Comment by pcav** [comment]
Maybe a rewrite helps here?
It seems to add more complexity than needed though:
https://serverfault.com/questions/177827/declaring-variable-in-htaccess-to-determine-deployment-environment
so feel free to close this if you think it is inappropriate.

**Comment by jordanbancino** [comment]
I'll take a look into it. I do think this is something we should work on.

**Comment by oupala** [comment]
The automation script would be the best solution.

See #107.

**Comment by jordanbancino** [comment]
@oupala Ok. I agree. Should we close this then?
