### ISSUE TITLE
Current Dockerfile is not working

### ISSUE THREAD

**Issue by PeterDaveHello** [oupala/apaxy#115]
The current `Dockerfile` and `apaxy/theme/htaccess.txt` they don't work happily together, all the icons are 404 not found, will need to fix it.

![image](https://user-images.githubusercontent.com/3691490/36772719-5284aae6-1c91-11e8-8439-4bdf79b906c4.png)

![image](https://user-images.githubusercontent.com/3691490/36772796-998510ca-1c91-11e8-9688-2f559743b7de.png)

**Comment by oupala** [comment]
Maybe @IntiGabriel (the original commiter of the Dockerfile) will want to update it?

**Comment by chrisssycollins** [comment]
@oupala @PeterDaveHello I've fixed in #103.
