### ISSUE TITLE
last modified time is in UTC even when system time is in IST

### ISSUE THREAD

**Issue by ankitg1989** [oupala/apaxy#118]
![selection_139](https://user-images.githubusercontent.com/20354406/37408058-5345f09e-27c1-11e8-9761-828a7dfec95f.png)

**Comment by oupala** [comment]
I think this is not linked to apaxy.

Can you try on a default index page without applying apaxy?

**Comment by oupala** [comment]
As there is no answer from my last comment, I will close the issue.
