### ISSUE TITLE
Community Profile

### ISSUE THREAD

**Issue by jordanbancino** [oupala/apaxy#119]
This repository follows very strict committing and contributing guidelines. It would be very beneficial to the maintainers of this project if we laid out exactly what we want and expect of our contributors in a `CONTRIBUTING.md` file. I could try to write one up later, but I think it'd be best if, @oupala, you could write it, as you facilitate the activities this project.

Also, would it be beneficial to add both issue and pull request templates? I found some really nice ones [here](https://github.com/stevemao/github-issue-templates/tree/master/simple) that I really like.

And, while I'm on the topic, how about a code of conduct? I'd say it's not necessary, but would be kind of nice to have. 

All of the above things I've mentioned can be found on [this page](https://github.com/oupala/apaxy/community).

**Comment by oupala** [comment]
I've added the default templates for issues (bug template, feature request template, and custom template). Let me know if you think this is not convenient for this project and if [issue templates from stevemao](https://github.com/stevemao/github-issue-templates/tree/master/simple) are better (and please tell me why).

We also have to think about a pull request template.

For the code of conduct, I'm thinking to use the one from [Contributor Covenant](https://www.contributor-covenant.org/). Do you have any opinion about that?

And last but not least, let me know if anyone knows a good CONTRIBUTE template.

**Comment by oupala** [comment]
I've just added a basic pull request template.

**Comment by jordanbancino** [comment]
Yep, looks good, I'd say we can close this one.

**Comment by oupala** [comment]
I'd like to add a CONTRIBUTE file before closing the issue.

**Comment by jordanbancino** [comment]
Ah I see, cool.
