### ISSUE TITLE
Filter content search box doesn't work?

### ISSUE THREAD

**Issue by dorianborovina** [oupala/apaxy#125]
Hi guys,

Thank you for such a wonderful theme!
On my installation instance filter content search box doesn't seem work.
Am I the only one or?

I have the script pointed out to the correct script location.
This is written in the **footer.html**

```js
<script src=/theme/apaxy.js></script>
```

Apaxy.js is the newest, I would say.
Any tips and tricks?
Thank you! 👍

**Comment by oupala** [comment]
It is strange that the path of the js file is an **absolut* path. It should probably be a relative path (without the initial slash **/**). Unless you have installed apaxy at the root level of your web server.

Can you check if you have some errors in the [web console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console) or some non loaded resources in the [network monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor)?

**Comment by dorianborovina** [comment]
Hi,
Thank you for your reply.
I have fixed one that problem, now I'm getting the other one.

_apaxy.js:7 Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined
    at apaxy.js:7_

**Comment by oupala** [comment]
Can you indicate the browser and version you're using?

What version of apaxy are you using? What branch of the git repo? Have you changed anything to any file (especially the header or the footer)?

Is your url public or private? (ie. can we have a look at it or not?)

Have you installed apaxy at the root level of your web server or not?

**Comment by the-nalexx** [comment]
Hi

`if (uri.substring(uri.length - 1) !== '/') {
  var indexes = document.getElementsByClassName('indexcolname');

  for (let i of indexes) {
    var a = i.getElementsByTagName('a')[0];
    a.href = '/' + a.getAttribute('href', 2);
  }
}`

**Comment by oupala** [comment]
@woodrowbarlow I do also see the same error on my dev instance. Can you please check if the search bar code needs optimization? @the-nalexx is proposing a new version of the code.

@the-nalexx I edited you message so that it renders better on GitHub. You can see this page to understand [how to beautifully format your code ins issues](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Comment by the-nalexx** [comment]
thank you !

**Comment by woodrowbarlow** [comment]
@oupala i didn't write that bit of code, [it has existed in apaxy since before you took over](https://github.com/oupala/apaxy/blob/af176b3932c01de23c32398c34eeb18e6f3b5b41/apaxy/theme/footer.html) - i just moved it into apaxy.js. i don't even know why it's necessary.

the solution posted by @the-nalexx seems sane to me.

**Comment by oupala** [comment]
You're right @woodrowbarlow sorry for being mistaken.

This code come from a very old commit made by @HazCod and @wblondel. Do you guys wanna fix this? Or do we take the change proposed by @the-nalexx?

**Comment by wblondel** [comment]
Hello,

I'm not sure to understand why I'm tagged on this issue, I don't remember contributing to this project at all...

@oupala  do you have a link to the commit? Thank you 😄

**Comment by oupala** [comment]
@wblondel I might have been mistaken, but you seem to be mentioned [in this commit](https://github.com/oupala/apaxy/commit/7d81d956b90b88613ba0fc159596ce396a76d954#diff-884c4be5e137f36f356d37892d2eea24).

**Comment by wblondel** [comment]
Oh, I see it now. Actually, I commented on this commit the following :

"Broken links since this commit. It does not affect links on icons though.
If I remove the new JS code, it works again
Config : Apache 2.4.17, on Windows"

It looks like I didn't know how to use "issues" at the time... ;)

**Comment by HazCod** [comment]
This was ages ago, and sadly I don't use apaxy anymore.
Best to revert that commit @oupala ?

**Comment by oupala** [comment]
If you don't want to maintain your commit, no problem @HazCod.

We'll try to take care of it by ourselves.

**Comment by oupala** [comment]
@the-nalexx Do you want to try to create a pull request for the change that you proposed earlier?

**Comment by the-nalexx** [comment]
The problem is I'm not sure of what you're asking of me. As I said, I have signed in to github yesterday and have barely never used a git.
The reason why came here was because of this bug : it occured to me, I fixed it, but instead of keeping it for myself I wanted to report my solution to all.

For now, I dont understand all... push, pull, commit, merge... Just use this code so that it serves everyone. I'll come back :D

**Comment by oupala** [comment]
Ok @the-nalexx, don't worry, I'll take care of applying your code to the codebase.

Thanks anyway and happy discovery of git and GitHub!

**Comment by oupala** [comment]
I fixed the issue following @the-nalexx proposal in commit f8670f0.

Thanks also @dorianborovina for finding the bug!

**Comment by SubrataM3** [comment]
Hi @oupala ,

I have this search issue also, I am using latest git version and nginx with fancyindex.
There is no error in the console log, also files (js,css,header,footer) are loading correctly.

footer.html (NOTE: apaxy folder is in document root.)
```
  <div class="block">
    {FOOTER-MESSAGE}
  </div><!--/.postlisting-->

</div><!--/.wrapper-->

<div class="footer">
  Apaxy by <a href="https://twitter.com/adamwhitcroft">@adamwhitcroft</a>
</div><!--/.footer-->
<script src=/apaxy/theme/apaxy.js></script>
```
I have a test server up with apaxy installed. Let me know if you want to see. (email would be better to send the server address. Posting IP in public causes lots of spammers to bruteforce server).
Thanks.

**Comment by oupala** [comment]
You can post your server ip on an instance of privatebin (such as [framabin](https://framabin.org/p/), with a short lifetime (around 1 week). What is the git commit of the version of apaxy that you're using?

**Comment by SubrataM3** [comment]
Ok, here is the [link](https://framabin.org/p/?3f2f429dc41a524b#+iMb6c+HVVfKZxU1qD/1uvmYiV+mICEbZ0BPinH5MOo=)
I have just cloned the repo an hour ago. so its the latest.
`9d15cc5 (HEAD -> develop, origin/develop, origin/HEAD) Merge branch 'master' into develop`

**Comment by oupala** [comment]
Here is your markup:

```html
<link href="/apaxy/theme/style.css" rel="stylesheet">
<div class="wrapper">
<!-- we open the `wrapper` element here, but close it in the `footer.html` file -->

<ol class="breadcrumb" id="breadcrumb">
</ol>

<input type="search" id="filter" placeholder="filter contents" />

{HEADER-MESSAGE}
<table id="list">
<thead>
  <tr>
    <th style="width:55%"><a href="?C=N&amp;O=A">File Name</a>&nbsp;<a href="?C=N&amp;O=D">&nbsp;&darr;&nbsp;</a></th>
    <th style="width:20%"><a href="?C=S&amp;O=A">File Size</a>&nbsp;<a href="?C=S&amp;O=D">&nbsp;&darr;&nbsp;</a></th>
    <th style="width:25%"><a href="?C=M&amp;O=A">Date</a>&nbsp;<a href="?C=M&amp;O=D">&nbsp;&darr;&nbsp;</a></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="link"><a href="../">Parent directory/</a></td>
    <td class="size">-</td>
    <td class="date">-</td>
  </tr>
  <tr>
    <td class="link"><a href="small.flv" title="small.flv">small.flv</a></td>
    <td class="size">296.2 KiB</td>
    <td class="date">2014-Feb-16 18:49</td>
  </tr>
  <tr>
    <td class="link"><a href="small.mp4" title="small.mp4">small.mp4</a></td>
    <td class="size">374.6 KiB</td>
    <td class="date">2014-Feb-16 18:49</td>
  </tr>
  <tr>
    <td class="link"><a href="small.ogv" title="small.ogv">small.ogv</a></td>
    <td class="size">428.0 KiB</td>
    <td class="date">2014-Feb-16 18:49</td>
  </tr>
  <tr>
    <td class="link"><a href="small.webm" title="small.webm">small.webm</a></td>
    <td class="size">224.1 KiB</td>
    <td class="date">2014-Feb-16 18:49</td>
  </tr>
  <tr>
    <td class="link"><a href="test.mp4" title="test.mp4">test.mp4</a></td>
    <td class="size">0 B</td>
    <td class="date">2019-Jun-07 12:47</td>
  </tr>
</tbody>
</table>  <div class="block">
    {FOOTER-MESSAGE}
  </div><!--/.postlisting-->

</div><!--/.wrapper-->

<div class="footer">
  Apaxy by <a href="https://twitter.com/adamwhitcroft">@adamwhitcroft</a>
</div><!--/.footer-->
<script src=/apaxy/theme/apaxy.js></script>
```

And here is my html markup:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Index of /files</title>
    <link rel="stylesheet" href="/files/theme/style.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/css/lightgallery.min.css" integrity="sha256-oPZ2OUkKul2aJQeDwKoO1p+DpvFR+w17n7YXydvFRWU=" crossorigin="anonymous">
    <div class="wrapper">
      <!-- we open the `wrapper` element here, but close it in the `footer.html` file -->
      <ol class="breadcrumb" id="breadcrumb"></ol>
      <input type="search" id="filter" placeholder="filter contents" />
      <table id="indexlist">
        <tr class="indexhead">
          <th class="indexcolicon"><img src="/files/theme/icons/blank.png" alt="[ICO]" /></th>
          <th class="indexcolname"><a href="?C=N;O=D">Name</a></th>
          <th class="indexcollastmod"><a href="?C=M;O=A">Last modified</a></th>
          <th class="indexcolsize"><a href="?C=S;O=A">Size</a></th>
        </tr>
        <tr class="even">
          <td class="indexcolicon"><a href="/"><img src="/files/theme/icons/folder-home.png" alt="[PARENTDIR]" /></a></td>
          <td class="indexcolname"><a href="/">Parent Directory</a></td>
          <td class="indexcollastmod">&nbsp;</td>
          <td class="indexcolsize">  - </td>
        </tr>
        <tr class="odd">
          <td class="indexcolicon"><a href="foldername/"><img src="/files/theme/icons/folder.png" alt="[DIR]" /></a></td>
          <td class="indexcolname"><a href="foldername/">foldername/</a></td>
          <td class="indexcollastmod">2016-07-29 03:08  </td>
          <td class="indexcolsize">  - </td>
        </tr>
        <tr class="even">
          <td class="indexcolicon"><a href="file.html"><img src="/files/theme/icons/html.png" alt="[html]" /></a></td>
          <td class="indexcolname"><a href="file.html">file.html</a></td>
          <td class="indexcollastmod">2019-03-02 16:15  </td>
          <td class="indexcolsize">4.3K</td>
        </tr>
      </table>
      <div class="block">
    {FOOTER-MESSAGE}
      </div>
      <!--/.postlisting-->
    </div>
    <!--/.wrapper-->
    <div class="footer">
      Apaxy by <a href="https://twitter.com/adamwhitcroft">@adamwhitcroft</a>
    </div>
    <!--/.footer-->
    <script src=/files/theme/apaxy.js></script>
  </body>
</html>
```

As you can see, your markup generated by nginx is slightly different from the one generated by apache.

**Comment by SubrataM3** [comment]
Thanks for your detailed answer 👍 .
1. Yes, search function works by modifying this [line](https://github.com/oupala/apaxy/blob/9d15cc5f267b8ec9122fc31ba98ceef7d8062e05/apaxy/theme/apaxy.js#L40) (it seems you have linked correct line, but pasted wrong line above).
2. I checked the code and found classname references like **indexhead**, **indexcolname** which is not available with nginx. Also lightgallery.js makes use of apache specific classname.
3. So, there are many minor adjustments needed to be done to make apaxy work with nginx.
If you are interested in doing that, i can help with nginx setup related task/testing server(if necessary) etc.

**Comment by oupala** [comment]
Thanks for the review. Ihave edited and fixed my previous comment.

If you're ok to maintain an nginx fork of apaxy, it is ok. We'll see if the changes are huge or not, if it needs to be a fork, a branch, or if we can improve apaxy to make it work with both apache and nginx.
