### ISSUE TITLE
Search in Header not working

### ISSUE THREAD

**Issue by kokotko1337** [oupala/apaxy#136]
Thanks for your theme, is very nice.

**Describe the bug**
Search field give no results

**To Reproduce**

1. type Filename
2. Click on 'Search'
3. nothing happens

**Expected behavior**
give results

**Desktop (please complete the following information):**
 - OS: w 10
 - Browser Chrome/FF/IE
 - Version latest

**Comment by oupala** [comment]
Hi, I'm not sure what you are talking about. In fact, there is no search button to click on. Could you please provide a non-working instance of apaxy?

The filter field is not a search engine, it is just a filtering field to filter wich files should be displayed or not.

**Comment by kokotko1337** [comment]
i got on Linux mounted some windows share and i think that is the problem why that not working ...

sorry ofc there is no search... I think Filter not working on mounted smb shares ...

**Comment by oupala** [comment]
Could you please test with a volume that is not a windows share, just to be sure?

**Comment by oupala** [comment]
I'm closing the issue as there is no response from @kokotko1337.

Feel free to reopen the issue if you feel this is needed.
