### ISSUE TITLE
Whic part of the dockerfile to i change to influence the root directory?

### ISSUE THREAD

**Issue by derrend** [oupala/apaxy#137]
Hi oupala, great job with the apaxy project!

Would you mind telling me which line of the Dockerfile i need to edit so i can make the share folder the default root rather than clicking into it each time i visit localhost when using docker-compose?

Thanks dude ;)

**Comment by oupala** [comment]
I don't understand what you mean. The behavior that you're looking for is the default behavior of the docker image:

https://github.com/oupala/apaxy/blob/cc02ee5e65359a95315d7d848589d4f4b05b8e14/Dockerfile#L4-L6

Don't you have the same behavior on your container?

**Comment by derrend** [comment]
Thanks for the response :)
What I mean to say is, when i access the / directory using docker-compose to bring up the container I am met with a bunch of demo files but i would like to map / to the /share directory, I'm not interested in displaying the demo files on my home network.
Is this possible?

**Comment by oupala** [comment]
The `share` directory is only there for people using the git version of apaxy.

If you're using the docker version of apaxy, just change the Dockerfile to serve the files that you want.

Depending on how you want to include the files in the container (static include inside the image, mount a volume), you will have to replace the following line with something like a `COPY` command, or with a volume to mount.

https://github.com/oupala/apaxy/blob/cc02ee5e65359a95315d7d848589d4f4b05b8e14/Dockerfile#L45

**Comment by derrend** [comment]
Figured it out.
Basically commented out the line highlighted in your previous comment and added my custom mounted volumes to the docker-compose file:
```
    volumes:
      - '/home/path_to/torrents/:/usr/local/apache2/htdocs/Torrents/'
      - '/media/path_to/Music/:/usr/local/apache2/htdocs/Music/'
      - '/media/path_to/Videos/:/usr/local/apache2/htdocs/Videos/'
      - '/media/path_to/Educational/:/usr/local/apache2/htdocs/Educational/'
```
Thanks again for the help! :+1:

**Comment by reyqn** [comment]
Just in case, I was having trouble hosting actual files in the root directory with this dockerfile (the solution mentioned here worked for hosting directories not files)

So I had to edit the dockerfile like this:

`RUN sed -i -e '/<Directory "\/usr\/local\/apache2\/htdocs">/r /usr/local/apache2/htdocs/.htaccess' /usr/local/apache2/conf/httpd.conf`

before the RUN for file_extension line to delete

Then also add a volume `- '/usr/local/apache2/htdocs/theme/'` to keep the theme from being shadowed from the volume in htdocs

Doing this you only need another volume before like `- './share/:/usr/local/apache2/htdocs/` and everything will be shared from the root with apaxy applied
