### ISSUE TITLE
Apaxy not working

### ISSUE THREAD

**Issue by signorettae** [oupala/apaxy#140]
I tried to install it on my Apache web server but it doesn't work. I tried with manual and automatic setup both

**Comment by oupala** [comment]
What should we do with such issue? No information, no detail, no clue.

I can just tell you that Apaxy **is working** on my server.

There should be something wrong on your side, but we need more information to find out what.

**Comment by atmgnd** [comment]
Is your sites configured with following setting?

<Directory "/var/www/html/share">
    AllowOverride All
    Options Indexes MultiViews FollowSymLinks
    Require all granted
</Directory>

**Comment by signorettae** [comment]
Thank you so much, I solved the problem

**Comment by signorettae** [comment]
> Is your site configured with following setting?
> 
> <Directory "/var/www/html/share">
>     AllowOverride All
>     Options Indexes MultiViews FollowSymLinks
>     Require all granted
> </Directory>

Thank you so much, I solved the problem
