### ISSUE TITLE
missing license for icons

### ISSUE THREAD

**Issue by DanielRuf** [oupala/apaxy#143]
I found no license file for the icons. It seems they are licensed under GPLv3, so I guess the project has to use GPLv3 too or at least add the license to the icons folder.

See https://choosealicense.com/licenses/gpl-3.0/

**Comment by oupala** [comment]
It seems that icons are part of the project since almost the first commit. That's why we never had the question about the license of icons. Maybe @AdamWhitcroft can help us about the history of the project.

What makes you think that icons are licensed under GPLv3?

**Comment by DanielRuf** [comment]
> What makes you think that icons are licensed under GPLv3?

According to https://www.deviantart.com/tiheum/art/Faenza-Icons-173323228

> This work is released under the GNU/GPL license. Sources can be downloaded here : [link]

And the files at https://code.google.com/archive/p/faenza-icon-theme/downloads

<img width="273" alt="Bildschirmfoto 2021-01-17 um 15 34 01" src="https://user-images.githubusercontent.com/827205/104846184-907a1700-58d9-11eb-8077-b235b66a94ac.png">
<img width="490" alt="Bildschirmfoto 2021-01-17 um 15 34 48" src="https://user-images.githubusercontent.com/827205/104846185-91ab4400-58d9-11eb-8b10-33c2b9c906d6.png">

**Comment by AdamWhitcroft** [comment]
This was a very long time ago, but I believe this was the set I used https://www.deviantart.com/tiheum/art/Faience-icon-theme-255099649 (GPLv3 as well). Hope that helps!

**Comment by oupala** [comment]
@DanielRuf Would you be ok to start a pull request for switching apaxy from Unlicense to GPL v3?

@AdamWhitcroft What's your opinion about switching to GPL v3?

**Comment by oupala** [comment]
According to the icons I checked (ie. ` rar.png` or `pres.png`), the icon set is more Faenza than Faience.

It might be time to choose a new set of icons, and tp embed it properly, with its license.

**Comment by AdamWhitcroft** [comment]
Sorry for the delay, no objections from me on changing the license.

**Comment by oupala** [comment]
In fact, I've just discovered that apaxy is using the Faenza icon set as stated in the README file since the [first commit](https://github.com/oupala/apaxy/commit/defcf2ab8326a3b28adc6b370a3a2f485f79a524#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R46):

> [Faenza Icons](http://tiheum.deviantart.com/art/Faenza-Icons-173323228) are used in the `apaxy` theme.

Besides, `apaxy` is licenced under the [Unlicence](https://unlicense.org/) licence and this licence is [compatible with the GPL v3 licence](https://www.gnu.org/licenses/license-list.en.html#Unlicense) of Faenza icons set. As a consequence, there is no need to change the licence of `apaxy`.

We just have to make sure that the requirement of GPL v3 from Faenza icons set are met.

**Comment by DanielRuf** [comment]
Sorry, I had not much time so far to check this in detail.

> We then have to change the license of `apaxy` from Unlicense to GPL v3.

Do we really have to change the license?

> I guess the project has to use GPLv3 too **or** at least **add the license to the icons folder**.

**Comment by oupala** [comment]
As stated in [gnu.org FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL), there is no reason to switch  ̀apaxy` to GPL v3 as Unlicence licence is compatible with GPL v3 licence (see my previous comment).

However, I'm a bit disturbed by the [following answer](https://www.gnu.org/licenses/gpl-faq.en.html#WhatDoesCompatMean):

> All GNU GPL versions permit such combinations privately; they also permit distribution of such combinations provided the combination is released under the same GNU GPL version.

I am now looking to the best way to include the Faenza icons set to apaxy.

**Comment by oupala** [comment]
Switching to GPL v3 is easy as the [Unlicence licence](https://unlicense.org/) is not holding copyright to authors:

> In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

As a consequence, the next release of `apaxy` will simply use GPL v3 licence.
