### ISSUE TITLE
Show current path

### ISSUE THREAD

**Issue by mfnalex** [oupala/apaxy#145]
Hi :)

In the default apache2 Autoindex, the current directory is displayed at the top, however it's missing in apaxy and I couldn't find a way to enable it. Is it somehow possible to get the current path shown at the top?

**Comment by oupala** [comment]
I don't understand why you say that the current directory is missing:

![screenshot](https://user-images.githubusercontent.com/13458743/106115311-ef992080-6150-11eb-978e-309952449947.png)

Can you please explain me why do you think there is something wrong?

**Comment by mfnalex** [comment]
Sorry, I actually the meant the "path" to the directory. E.g. /folder1/folder2/currentfolder

**Comment by oupala** [comment]
Yes, the path to the directory appears at the top of the windows. See the following screenshot:

![screenshot](https://user-images.githubusercontent.com/13458743/106193513-e8543000-61ad-11eb-903b-b17ba57d1992.png)

I still don't understand your issue.

Can you tell me if **I** get your issue wrong, or if **you** have not seen it?

**Comment by mfnalex** [comment]
I downloaded the latest release from GitHub and I do not see the the directory.

![image](https://user-images.githubusercontent.com/1122571/106250564-19674b80-6214-11eb-8ef2-03a48be3cd68.png)
https://repo.jeff-media.de

**Comment by oupala** [comment]
The breadcrumb is generated by a piece of javascript located in `apaxy.js`. This javascript file is loaded at the end of the [`footer.html`](https://github.com/oupala/apaxy/blob/develop/apaxy/theme/footer.html#L10). Your problem might be that this javascript file is not loaded.

Have followed the [install guide](https://github.com/oupala/apaxy#installation)?

**Comment by mfnalex** [comment]
Thanks, I forgot to edit the footer.html.
