### ISSUE TITLE
Not working with sub directories

### ISSUE THREAD

**Issue by 1manfactory** [oupala/apaxy#146]
I wouldn't call it a bug.

But this does not work with sub directory browsing. Or you would have to place an edited .htaccess file in every sub directory which of course is not very practical.

Do you have any ideas how to bypass this problem?

**Comment by oupala** [comment]
As you can see in screeshots from #145, it is indeed working in subdirectories.

Have you configured apaxy manually or using the bash script?

Have you followed the [install guide](https://github.com/oupala/apaxy#installation) with care?

**Comment by oupala** [comment]
Friendly reminder about this issue. Have tried to fix your problem following the install guide?

Should I close this issue?

**Comment by 1manfactory** [comment]
Hello. Thanks four your help. I managed to solve it.
