### ISSUE TITLE
combine Apaxy with htpasswd / Basic Auth

### ISSUE THREAD

**Issue by DanielRuf** [oupala/apaxy#147]
**Is your feature request related to a problem? Please describe.**
I want to use basicauth and custom PHP + JS scripts to read some user provided data.
In my case the name of the logged in user is shown by using an AJAX request to a simple PHP script.

**Describe the solution you'd like**
Pass through the basicauth details to PHP. Add some details to the documentation.

`SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0`
or
`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`

https://stackoverflow.com/questions/4947548/what-does-this-this-http-authorization-rewriterule-do

**Describe alternatives you've considered**
Not sure.

**Additional context**

**Comment by oupala** [comment]
I'm not sure about your intents.

Are you willing to add some php script to apaxy git repo? Some apache configuration?

Are you asking for support in order to achieve something on your website?

Please complete this issue in the comments in order to tell us what are your plans, or your intent.

**Comment by DanielRuf** [comment]
> Some apache configuration?

Some documentation for this use case.

**Comment by oupala** [comment]
So I believe your question has nothing specific to apaxy. You should ask for support in a generic apache place.

**Comment by DanielRuf** [comment]
> Add some details to the documentation.

It's mostly about this (documenting this use case).

> So I believe your question has nothing specific to apaxy. You should ask for support in a generic apache place.

It already works. I think there is a misunderstanding.

I think I can close the issue as it might not be needed to document as possible use case.

**Comment by oupala** [comment]
Oh I see now. And yes you're right, I did not understand that you were proposing a specific usecase, not asking for help. Sorry for the misunderstanding. And thank you for your contribution. I think issues is a good place for keeping track of some usecases that are not widely used.
