### ISSUE TITLE
Demo or screenshots

### ISSUE THREAD

**Issue by trensetim** [oupala/apaxy#150]
I would love to see a couple more screenshots or even a running demo. 

**Describe the solution you'd like**
The screenshot that's placed on the referred website looks promising. It would be even better to have a couple more to really show off the look and feel of the chosen theme. 

**Describe alternatives you've considered**
Either just host a couple demo files on a private Webserver with this project enabled on it or create enough screenshots to get a feeling for how it looks.

**Comment by oupala** [comment]
The presentation website of apaxy is hosted by GitHub pages at <https://oupala.github.io/apaxy/>. There is already [a screenshot](https://oupala.github.io/apaxy/img/example.png) on this website:

![apaxy screenshot](https://oupala.github.io/apaxy/img/example.png)

In your issue, you say that you want to show more screenshots. But what more do you want to show?

And by the way, it is not possible to host a demo of apaxy on GitHub pages as GitHub pages is using another http server:

> server : GitHub.com

Do you have any private webserver to host a demo of apaxy?

**Comment by oupala** [comment]
Feel free to open a merge request with some more screenshots, or a demo server of apaxy.
