### ISSUE TITLE
"Filtering Content" not working.

### ISSUE THREAD

**Issue by OneFathom** [oupala/apaxy#157]
**Describe the bug**
When typing in a file name to filter for a specific file, nothing is filtered.

**To Reproduce**
1. Go to ---
2. Click on "filter content" text input
3. Type: "12771"
4. This should filter the table below and only show "G0012771.JPG"

**Expected behavior**
As I type in this text field, I should see the below table of images filter based on the text I input.

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Mozilla Firefox and Microsoft Edge
 - Version 127.0.2 and 126.0.2592.81

**Additional context**
![Screenshot 2024-07-01 145438](https://github.com/oupala/apaxy/assets/174386702/e5c108cb-6a2c-494a-8de0-7986a7b228bb)

**Comment by OneFathom** [comment]
I'm an idiot, didn't finish reading the instructions...

> edit "footer.html", along with all the other "html" documents (in the "/share/theme" folder) and update all instances of paths marked with *{FOLDERNAME}* to point to your site root
> 
> So...
> 
> ```html
> <script src={FOLDERNAME}/theme/apaxy.js></script>
> ```
> 
> Should be changed to...
> 
> ```html
> <script src=/share/theme/apaxy.js></script>
> ````

**Comment by oupala** [comment]
If you don't mind, I will close the issue. Please reopen it if needed.
