### ISSUE TITLE
Add Pagination

### ISSUE THREAD

**Issue by OneFathom** [oupala/apaxy#158]
**Is your feature request related to a problem? Please describe.**
For large indexes of files, it would be nice to have a pagination to browse content by page.

**Describe the solution you'd like**
Where a user can use links such as "next", "previous", and page numbers to navigate between pages that display one page of results at a time. Load more: Buttons that a user can click to extend an initial set of displayed results.

**Comment by oupala** [comment]
apaxy is only a way to style the default apache index page. It cannot easily add feature that are not in the original unstyled page.

I advise you to create directories and subdirectories if there is too muche files in your (root) directory.

You can also use filtering to display only desired files.
