### ISSUE TITLE
Can we have apaxy in the root folder itself?

### ISSUE THREAD

**Issue by endahargaden** [oupala/apaxy#159]
I have apaxy working well on my server at mysite.com/share and the world is well in that folder. To do this, I have placed the .htaccess one level above /share/ so in the root "mysite.com" folder. However, I would like the entirety of mysite.com to act as a repository.

To be a little more specific, I am not sure this is a feature request more so than a problem with my installation. You can see the actual difference between enda dot space (which gives a default Apache page) versus enda dot space /beamertheme (which works well). There are files in the root folder (consider robots.txt) that I would like listed by apaxy.

Is this possible?

**Comment by oupala** [comment]
I'm not about your issue @endahargaden.

The default image built and run by the `docker-compose.yml` file is an example of apaxy installed at the rool level of the apache server.

So yes, it is possible to run apaxy at the root level of apache.
