### ISSUE TITLE
Syntax error in /apaxy/theme/apaxy-lightgallery.js

### ISSUE THREAD

**Issue by TechnologyMan101** [oupala/apaxy#160]
**Describe the bug**
Lines 2 and 3 in the file `/apaxy/theme/apaxy-lightgallery.js` are missing a comma. This causes a syntax error, so lightgallery does not work when enabled. 

**To Reproduce**
1. Install Apaxy with lightgallery
2. Open an image in an indexed directory on the web server
3. The image opens directly instead of using lightgallery

**Expected behavior**
The image should have opened in lightgallery. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 131

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 14
 - Browser Firefox
 - Version 131

**Additional context**
Adding the 2 missing commas fixes the issue.

**Comment by oupala** [comment]
fixed by merge request #161
