### ISSUE TITLE
Images could be optimized to be more light

### ISSUE THREAD

**Issue by nicolasdanelon** [oupala/apaxy#33]
Using [trimage](http://trimage.org/) program you can lower the weights of images

![screenshot from 2014-11-11 18 45 46](https://cloud.githubusercontent.com/assets/2846046/5001317/729b9ebc-69d3-11e4-8604-c22bbbb1a733.png)
![screenshot from 2014-11-11 18 45 58](https://cloud.githubusercontent.com/assets/2846046/5001319/729c6a72-69d3-11e4-9866-35cbc4c18279.png)
![screenshot from 2014-11-11 18 45 55](https://cloud.githubusercontent.com/assets/2846046/5001318/729bd418-69d3-11e4-92f3-b81cf4708331.png)
![screenshot from 2014-11-11 18 45 38](https://cloud.githubusercontent.com/assets/2846046/5001320/729f9ad0-69d3-11e4-843c-cb076ae8a65e.png)

**Comment by oupala** [comment]
New icons set is coming. It will hopefully already be optimized.
