### ISSUE TITLE
Nginx compatibility

### ISSUE THREAD

**Issue by angristan** [oupala/apaxy#51]
Any plan on Nginx compatibility ? :)

**Comment by matunixe** [comment]
Hey, That would be very nice !

**Comment by maxvodo** [comment]
:+1:

**Comment by AdamWhitcroft** [comment]
@Angristan no idea, but I'll do what I can to look into it.

**Comment by bugparty** [comment]
using nginx thirdparty fancyindex module can solve this problem

**Comment by archeonkhan** [comment]
I'd like to bump this, would love to see this on nginx.

**Comment by Angristan** [comment]
Maybe this could help: https://www.nginx.com/resources/wiki/modules/fancy_index/

**Comment by oupala** [comment]
Has anyone tested apaxy compatibility with Nginx? Otherwise we might be obliged to close the issue if no one is using Ninx.

**Comment by oupala** [comment]
As [Nginx document says](https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/):

> You can’t do this. You shouldn’t. If you need .htaccess, you’re probably doing it wrong.

As a consequence, Apaxy will probably don't work out-of-the-box with Nginx, while **it could work** with a bit of tuning.

**Comment by bugparty** [comment]
It does works if fancyindex  installed with nginx

**Comment by SubrataM3** [comment]
Can anyone share working configuration ?
The only thing i can't find in nginx is equivalent directives for **AddIcon** and **AddIconByType**  .

**Comment by bugparty** [comment]
make sure you installed fancyindex

**Comment by SubrataM3** [comment]
> make sure you installed fancyindex

Yes, I am sure that fancyindex is installed and working properly.

**Comment by bugparty** [comment]
maybe you should delete these directives, apaxy has no AddIcon in 2016, these directives are not essential
