### ISSUE TITLE
.zip is missing from the Archive files list in htaccess.txt

### ISSUE THREAD

**Issue by hartsook** [oupala/apaxy#52]
You have the icon included, but left out .zip with the other archive file types in the htaccess.txt file.

**Comment by tcyrus** [comment]
@hartsook, I believe this is because `.zip` files have their own icon

**Comment by AdamWhitcroft** [comment]
@hartsook `AddIcon /theme/icons/zip.png .zip` will apply a zip icon to a zip file. Are there some other formats you'd like me to add in there?

**Comment by oupala** [comment]
This issue has been resolved and @hartsook does not seem to answer back.

I'm closing this issue. Feel free to comment if you want some more informations.
