### ISSUE TITLE
Use local copy of the Open Sans font

### ISSUE THREAD

**Issue by nodiscc** [oupala/apaxy#59]
Hi, I've noticed Apaxy requests the Open Sans font from `fonts.googleapis.com` + `fonts.gstatic.com` (https://github.com/AdamWhitcroft/Apaxy/blob/master/apaxy/theme/style.css#L8). Would you be OK to include this font in the release archive, and use that copy by default instead?

Some advantages: No cross-site requests, no leaking of HTTP Referers to font provider, works on LAN-only setups, no dependency on an external service, only 1 connection initiated.

The Google Fonts `@include` can be left commented out for users that want to re-enable it.

The current TTF fonts used by fonts.googleapis.com can be found at https://github.com/google/fonts/tree/master/apache/opensans. I can start working on a patch, including a Makefile to fetch the latest version from there.

**Comment by AdamWhitcroft** [comment]
@nodiscc sounds good to me. Did you get round to making that Makefile?

**Comment by nodiscc** [comment]
Not yet. I will look into that soon.

**Comment by jordanbancino** [comment]
The changes in #109 also use the external fonts, so if we wish to fix this, the error pages will have to be updated as well.

**Comment by oupala** [comment]
I agree with @nodiscc, we have to fix this issue. The advantage he lists are important:

> Some advantages: No cross-site requests, no leaking of HTTP Referers to font provider, works on LAN-only setups, no dependency on an external service, only 1 connection initiated.

Should we add a script (but it should be platform independent, make is not availabel everywhere, see #107), or should we include the font statically?

**Comment by nodiscc** [comment]
> I will look into that soon.
> Oct 5, 2016

Famous last words. Sorry I actually forgot about this, and I don't think I will have time to work on it. What I would do, in order of preference:

 - Don't include the font, browsers with an available local Open Sans font will display it fine, and those who don't will provide a reasonable fallback.
 - Provide a bundled Open Sans as part of tagged releases (https://help.github.com/articles/creating-releases/ point 7. - attach a zip file with Apaxy + fonts)
 - Download the font as part of the install script (#107)
 - Include the font in the git repository (large files)
 - Include the font in the git repository

**Comment by oupala** [comment]
I agree with your proposal.

Depending on the install automation script (see #107), we'll see what solution we will choose.

**Comment by oupala** [comment]
While testing apaxy, even if the OpenSans font is still imported:

https://github.com/oupala/apaxy/blob/10de49ea5128b6b6d31929f7a40245c765486a5b/apaxy/theme/style.css#L12

I can't find any request to Google to import the font, in the network tab of Firefox developer tools.

Does anyone know why?

**Comment by jordanbancino** [comment]
Maybe the user can just configure this on their own, as this might  be a little hard to do automatically, but nevertheless, I can take a look.

**Comment by oupala** [comment]
I will remove the Open Sans font from apaxy.
