### ISSUE TITLE
character encoding

### ISSUE THREAD

**Issue by Tom7320** [oupala/apaxy#71]
Hi!

Unfortunately character encoding does not work on my site (http://dl.billroth.de/):
![2016-08-08_17h38_03](https://cloud.githubusercontent.com/assets/19165864/17485808/0ad7248e-5d8f-11e6-8c91-24e6fd3aa168.png)
How can I fix that?

THX a lot!

**Comment by nask0** [comment]
Add to your .htaccess :
```
AddDefaultCharset UTF-8
```

**Comment by AdamWhitcroft** [comment]
@Tom7320 did @nask0's suggestion solve the issue for ya?

**Comment by AdamWhitcroft** [comment]
@Tom7320 Following up again; has the above been resolved for you?

**Comment by oupala** [comment]
Closing issue as @Tom7320 does not answer.
