### ISSUE TITLE
Can't get Header and Footer to load!

### ISSUE THREAD

**Issue by akacross** [oupala/apaxy#72]
![screenshot 2016-08-20 10 23 36](https://cloud.githubusercontent.com/assets/20848591/17831772/6e8efa3a-66c0-11e6-827f-ed7af535d80a.png)

i am using Wampserver 3, Apache version is in the screenshot.

**Comment by ScottSmudger** [comment]
By having:
```
HeaderName theme/header.html
ReadmeName theme/footer.html
```

In your htaccess file should fix this

**Comment by AdamWhitcroft** [comment]
@akacross Did @ScottSmudger solve this for you?

**Comment by pcav** [comment]
I do have it, but only standard header and footer is displayed:
http://www.faunalia.eu/salgrid_repo_test/
Thanks for any hint.

**Comment by pcav** [comment]
Strangely enough, on another install head and foot work. Maybe there are permission issues, I have to check. I'll report back for the record as soon as I get it.

**Comment by oupala** [comment]
Issue seems fixed.

I'm closing it.

**Comment by pcav** [comment]
-rw-r--r-- 1 paolo paolo  861 Jan 29 16:35 footer.html
-rw-r--r-- 1 paolo paolo  159 Feb 18 20:38 header.html
