### ISSUE TITLE
Where to put on macOS, using XAMPP?

### ISSUE THREAD

**Issue by gusbemacbe** [oupala/apaxy#73]
On XAMPP folder, there is a `shared` folder, but there is not `themes` folder.

**Comment by AdamWhitcroft** [comment]
The `themes` folder is part of Apaxy.

- Download and unzip Apaxy
- Copy the contents of `Apaxy-master/apaxy` to the directory you want to use it in
- Follow the rest of the instructions [here](https://github.com/AdamWhitcroft/Apaxy#installation)

**Comment by gusbemacbe** [comment]
It didn't work.

1. I moved the folder `apache`from the folder `Apaxy-master`  to `/Applications/XAMPP/xamppfiles/htdocs` and also moved the file `apache-config.conf` to `/Applications/XAMPP/xamppfiles/htdocs`.
2. I modified to `DocumentRoot /Applications/XAMPP/xamppfiles/htdocs` in the file `apache-config.conf`.
3. I also added in the file `httpd.conf` from the path `/Applications/XAMPP/xamppfiles/etc/httpd.conf`:
```
# Apache Autodindex page elegant style theme
Include /Applications/XAMPP/xamppfiles/htdocs/apache-config.conf
```

4. I restarted XAMPP.

**Comment by oupala** [comment]
@gusbemacbe Have you solved the issue? If no, we might be obliged to close the issue as it seems that on one is using XAMPP here.

**Comment by gusbemacbe** [comment]
Yes, I did, you can close now.

**Comment by oupala** [comment]
Ok, I'm closing the issue.

Do not hesitate to share your solution with us. It might be useful for others.

**Comment by gusbemacbe** [comment]
When I will be on holidays (on 7 December), I will make a tutorial to share with you.
