### ISSUE TITLE
Litespeed?

### ISSUE THREAD

**Issue by tylerscochran** [oupala/apaxy#74]
Will/should Apaxy work on a Litespeed server?  Are there additional configuration considerations... since Litespeed servers handle Apache configs the same?

**Comment by AdamWhitcroft** [comment]
Sorry, but I honestly couldn't answer this for you. I have no experience with Litespeed servers or their configurations.

**Comment by oupala** [comment]
@tylerscochran Are you willing to test apaxy compatibility with litespeed?

**Comment by oupala** [comment]
It is as you want. I don't know anything about litespeed servers. So I cannot help directly.

**Comment by oupala** [comment]
As [LiteSpeed documentation says](https://www.litespeedtech.com/solutions):

> Apache Drop-in Replacement
> Reads Apache config files directly, supports .htaccess

So it should work!
