### ISSUE TITLE
inline javascript does not comply Content Security Policies

### ISSUE THREAD

**Issue by oupala** [oupala/apaxy#83]
apaxy homepage contains some inline javascript (see [these lines](/AdamWhitcroft/apaxy/blob/master/apaxy/theme/footer.html#L10-L23)).

[Content Security Policy](https://content-security-policy.com/) encourage to move inline javascript into a separate javascript file and **not** to use `script-src 'unsafe-inline'`.

apaxy should move inline javascript into a separate javascript file.

**Comment by oupala** [comment]
I created a pull request about that into #84

**Comment by oupala** [comment]
By the way, I wonder what it this javascript useful for?

Everything seems to work even without this piece of javascript. Am I missing a specific feature?

**Comment by oupala** [comment]
Are you willing to merge this request or not?

Is there a problem with my code? Should I improve it in a specific way?

**Comment by rivermont** [comment]
@oupala Can this be closed now that the pull was merged?

**Comment by oupala** [comment]
You're right!
