### ISSUE TITLE
combine with .htpasswd ?

### ISSUE THREAD

**Issue by edd--** [oupala/apaxy#87]
Hi,

I would like to combine apacy with basic authentication.

When I try to add:

AuthName "secure"
AuthUserFile .htpasswd
AuthType Basic
Require valid-user

I get a server error ...

Any idea how to solve this ?

thank you,

Edd--

**Comment by nicozimmermann94** [comment]
I guess apache cannot find your .htpasswd file. The path has to be absolute and not relative. So instead of `AuthUserFile .htpasswd` try something like `AuthUserFile /var/www/html/mydir/.htpasswd`

**Comment by oupala** [comment]
I managed to use apaxy in combination with an `.htpasswd` file. There is no conflict between them.

So there should be a solution to your problem. @edd--, have you tried @nicozimmermann94 solution?

**Comment by oupala** [comment]
As there is no answer from @edd--, I will soon close the issue.
