### ISSUE TITLE
Does this work with lighttpd?

### ISSUE THREAD

**Issue by robsd** [oupala/apaxy#91]
Does this theme work with lighttpd aka. lighty?

It's similar to Apache but more lightweight.
It has the ability to add a custom CSS file so I thought it shouldn't be pretty hard to get it working.

**Comment by jordanbancino** [comment]
It all depends on how `lighttpd` generates it's directory indexes. Also, does it support all of the things in `.htaccess`? If it does, then yes, apaxy should work with lighttpd. I'll do some research on this.

**Comment by oupala** [comment]
@jordanbancino Did you had time to work on lightttpd compatibility?

**Comment by oupala** [comment]
As Nginx (see #51), [lighttpd documentation](https://redmine.lighttpd.net/projects/lighttpd/wiki/FrequentlyAskedQuestions#Do-you-support-htaccess-files)  says that lighttpd does not support htaccess files:

> Do you support .htaccess files?
> 
> No. Lightys design does not permit implementing this functionality as config files are loaded at startup time and .htaccess would be needed to be parsed at request time.
> Also scanning all the directories in the request path for those files can cause significant slowdown especially because lighty is single process and single threaded.
> Furhtermore, .htaccess files are Apache config files. We would need to write a parser and it might not even be possible to map all functionality to lighty logic.

As a consequence, Apaxy will probably don't work out-of-the-box with lighttpd, while **it could maybe work** with a bit of tuning.
