### ISSUE TITLE
Set default sort order

### ISSUE THREAD

**Issue by mR12KL** [oupala/apaxy#92]
I want to set the default sort order to be ?C=M;O=D

How can I set this! Thanks.

**Comment by UksusoFF** [comment]
http://httpd.apache.org/docs/trunk/mod/mod_autoindex.html#IndexOrderDefault

**Comment by oupala** [comment]
Can we close this issue?

**Comment by jordanbancino** [comment]
Yeah, this isn’t an Apaxy issue. Let’s close it. @oupala
