### ISSUE TITLE
Hide DOT files?

### ISSUE THREAD

**Issue by SychO9** [oupala/apaxy#93]
Hello,
in my directory listing .htaccess and some other dot files are showing up, I'de like them to be hidden, is that possible ?

thanks in advance.

**Comment by nodiscc** [comment]
https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html#indexignore

**Comment by SychO9** [comment]
Thank You

**Comment by rivermont** [comment]
@SychO9 Did that link resolve your issue?
