### ISSUE TITLE
Can't change <title> without using +SuppressHTMLPreamble which breaks style

### ISSUE THREAD

**Issue by alexfoxetech** [oupala/apaxy#97]
As above, I believe +SuppressHTMLPreamble prevents some of the HTML that apaxy extends from being generated in the first place meaning the page does not render correctly at all, are there plans to update apaxy to not be reliant on the default html so we can change the <title> tags?

**Comment by oupala** [comment]
I did not understood your issue. Could you please explain it once again?

**Comment by alexfoxetech** [comment]
Basically I want to change the <title> value of the directory. If I add a <title> to header.html it doesn't work as it actually appears in the body of the document. I cannot use IndexHeadInsert as this just appends another <title> to the header.. Is there anyway to change the title in apaxy?

**Comment by oupala** [comment]
I tested to reproduce your problem, and I can't see any easy way to achieve what you want to.

As you said, adding the `title` tag to `header.html` adds it in the body.

Using the `IndexHeadInsert` directive just appends another `title` tag to the header, which is ignored by the browser as it is the second `title` tag.

Maybe you can report in `header.html` the beginning of the default header that you remove when you use the `SuppressHTMLPreamble` directive.

**Comment by alexfoxetech** [comment]
Yes this is what I originally did, but using SuppressHTMLPreamble seems to break Apaxy in my tests.

**Comment by alexfoxetech** [comment]
Ok, no problem, I wasn't closing the correct tags in the footer.html file. All sorted, thank you :)
