### ISSUE TITLE
Custom Error Pages

### ISSUE THREAD

**Issue by rivermont** [oupala/apaxy#98]
It would be great to have custom HTTP error pages to go with the theme. Will look into this myself.

**Comment by jordanbancino** [comment]
Oh yes. This would be very easy. Just adding these to the `.htaccess` file would redirect apache to these pages instead:

    ErrorDocument 404 /errors/not_found.html
    ErrorDocument 403 /errors/forbidden.html

Of course, we could do more errors, and put their pages where ever we want.

**Comment by jordanbancino** [comment]
Oh, we could also do something like this:

    ErrorDocument 500 "The server encountered an error"

But that wouldn't be a styled error page...

Anyway, [this article](https://httpd.apache.org/docs/2.4/custom-error.html) has lots of good information on this.

**Comment by oupala** [comment]
Does anyone plan to write such an error page?

**Comment by jordanbancino** [comment]
Yes. I can do it.

**Comment by oupala** [comment]
Good @jordanbancino. Feel free to reference this issue in your pull request.

**Comment by jordanbancino** [comment]
@oupala Awesome, I’ll get to work.
